#!/bin/bash

n_r="npm run"

cd app/ || exit 1

for i in "$@"; do
	case $i in
		-d|--dev)
		shift
		"$n_r" dev
		exit 0
		;;
		-dd|--debug)
		shift
		"$n_r" dev:debug
		exit 0
		;;
		-b|--build)
		"$n_r" build
		exit 0
		;;
		*)
		echo "$@" && echo "Unknown opt"
		exit 1
		;;
	esac
done
