#!/bin/bash

n="npm"
x="npx"

v="vite"
r="run"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

go_to () {
	cd "$SCRIPT_DIR/app" || exit 1
}


for i in "$@"; do
	case $i in
		-i|--install)
		shift 
		go_to
		$n install
		exit 0
		;;
		-d|--dev)
		shift
		go_to
		$n $r dev
		exit 0
		;;
		-vi|--vite)
		shift
		go_to
		$x tsc && $x $v build && G_MESSAGES_DEBUG=all electron .
		exit 0
		;;
		-e|--electron)
		shift
		go_to
		electron .
		exit 0
		;;
		-dd|--debug)
		shift
		go_to
		$n $r dev:debug
		exit 0
		;;
		-b|--build)
		go_to
		$n $r build
		exit 0
		;;
		*)
		go_to
		"$@"
		exit 0
		;;
	esac
done
